services:
  app:
    image: yulmoo/springboot:latest
    container_name: springboot-app
    env_file:
      - .env.prod     # 실제 서버에서 제공
    ports:
      - "80:8080"
    depends_on:
      springboot-mysql:
        condition: service_healthy
    restart: unless-stopped

  springboot-mysql:
    image: mysql:8.0.43
    container_name: springboot-mysql
    env_file:
      - .env.prod
    command: [
      "--default-authentication-plugin=caching_sha2_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - ./_vol/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped